anchor_version = "0.24.2"
solana_version = "1.9.12"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# wallet = "./tests/test_key.json"
wallet = "/Users/nineowls/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [[test.genesis]]
# address = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"
# program = "./artifacts/programs/stable_swap.so"

# [programs.mainnet]
# lockup = "LockKXdYQVMbhhckwH3BxoYJ9FYatcZjwNGEuCwY33Q"
# mint_proxy = "UBEBk5idELqykEEaycYtQ7iBVrCg6NmvFSzMpdr22mL"

# [programs.devnet]
# lockup = "LockKXdYQVMbhhckwH3BxoYJ9FYatcZjwNGEuCwY33Q"
# mint_proxy = "UBEBk5idELqykEEaycYtQ7iBVrCg6NmvFSzMpdr22mL"

# [programs.testnet]
# lockup = "LockKXdYQVMbhhckwH3BxoYJ9FYatcZjwNGEuCwY33Q"
# mint_proxy = "UBEBk5idELqykEEaycYtQ7iBVrCg6NmvFSzMpdr22mL"

# [programs.localnet]
# lockup = "LockKXdYQVMbhhckwH3BxoYJ9FYatcZjwNGEuCwY33Q"
# mint_proxy = "UBEBk5idELqykEEaycYtQ7iBVrCg6NmvFSzMpdr22mL"
